package com.openclassrooms.realestatemanager

/**
 * Contains RealEstateManager application constant values.
 */
object AppInfo {

    // SharedPreferences parameters
    const val FILE_SHARED_PREF = "FILE_SHARED_PREF"
    const val PREF_PERMISSIONS = "PREF_PERMISSIONS"
    const val PREF_PERMISSION_LOCATION = "PREF_PERMISSION_LOCATION"
    const val PREF_CURRENCY = "PREF_CURRENCY"
    const val PREF_CURRENT_URI = "PREF_CURRENT_URI"
    const val PREF_USER_LOC_LATITUDE = "PREF_USER_LOC_LATITUDE"
    const val PREF_USER_LOC_LONGITUDE = "PREF_USER_LOC_LONGITUDE"

    // Request codes
    const val REQUEST_PERMISSIONS_CODE = 101
    const val REQUEST_IMAGE_GALLERY = 1
    const val REQUEST_IMAGE_CAPTURE = 2

    // Bundle keys
    const val DIALOG_RESET_KEY = "DIALOG_RESET_KEY"
    const val DIALOG_CANCEL_KEY = "DIALOG_CANCEL_KEY"
    const val DIALOG_ADD_MEDIA_KEY = "DIALOG_ADD_MEDIA_KEY"
    const val DIALOG_CONFIRM_MEDIA_KEY = "DIALOG_CONFIRM_MEDIA_KEY"
    const val DIALOG_LIST_AGENTS_KEY = "DIALOG_LIST_AGENTS_KEY"
    const val DIALOG_CONFIRM_SELL_KEY = "DIALOG_CONFIRM_SELL_KEY"
    const val DIALOG_ADD_AGENT_KEY = "DIALOG_ADD_AGENT_KEY"
    const val FIRST_NAME_AGENT_KEY = "FIRST_NAME_AGENT_KEY"
    const val LAST_NAME_AGENT_KEY = "LAST_NAME_AGENT_KEY"
    const val DIALOG_LOGOUT_KEY = "DIALOG_LOGOUT_KEY"
    const val DIALOG_ADD_POI_KEY = "DIALOG_ADD_POI_KEY"
    const val TEXT_DIALOG_CONFIRM_MEDIA_KEY = "TEXT_DIALOG_CONFIRM_MEDIA_KEY"
    const val UPDATE_ESTATE_KEY = "UPDATE_ESTATE_KEY"
    const val NUMBER_PHOTO_KEY = "NUMBER_PHOTO_KEY"
    const val CONFIRM_EXIT_KEY = "CONFIRM_EXIT_KEY"
    const val ESTATE_AGENT_KEY = "ESTATE_AGENT_KEY"
    const val DIALOG_CURRENCY_SELECT_KEY = "DIALOG_CURRENCY_SELECT_KEY"
    const val DIALOG_DELETE_ACCOUNT_KEY = "DIALOG_DELETE_ACCOUNT_KEY"
    const val ERROR_SLIDERS_KEY = "ERROR_SLIDERS_KEY"

    // Bundle keys - Search Fragment
    const val DIALOG_RESET_FILTERS_KEY = "DIALOG_RESET_FILTERS_KEY"
    const val DIALOG_SEARCH_KEY = "DIALOG_SEARCH_KEY"
    const val CHECKBOX_PRICE_KEY = "CHECKBOX_PRICE_KEY"
    const val CHECKBOX_SURFACE_KEY = "CHECKBOX_SURFACE_KEY"
    const val CHECKBOX_DATE_KEY = "CHECKBOX_DATE_KEY"
    const val CHECKBOX_STATUS_KEY = "CHECKBOX_STATUS_KEY"
    const val CHECKBOX_POI_KEY = "CHECKBOX_POI_KEY"
    const val NETWORK_BAR_STATUS_KEY = "NETWORK_BAR_STATUS_KEY"

    // Tags
    const val TAG_FRAGMENT_NEW_ESTATE = "TAG_FRAGMENT_NEW_ESTATE"
    const val TAG_FRAGMENT_SETTINGS = "TAG_FRAGMENT_SETTINGS"
    const val TAG_FRAGMENT_LIST_ESTATE = "TAG_FRAGMENT_LIST_ESTATE"
    const val TAG_FRAGMENT_ESTATE_DETAILS = "TAG_FRAGMENT_ESTATE_DETAILS"
    const val TAG_FRAGMENT_MAP = "TAG_FRAGMENT_MAP"
    const val TAG_FRAGMENT_SEARCH = "TAG_FRAGMENT_SEARCH"

    // Notification parameters
    const val CHANNEL_ID = "CHANNEL_ID"
    const val CHANNEL_NAME = "channel_real_estate_manager_app"

    // LocationListener parameters
    const val LOCATION_REFRESH_TIME: Long = 15000
    const val LOCATION_REFRESH_DISTANCE: Float = 10f

    // Map parameters
    const val DEFAULT_CAMERA_ZOOM = 18.0f
}